apiVersion: v2
name: helm-capi-cluster-template
description: A Helm chart for public cloud cluster with Cluster API
maintainer: Lucious Johnny Cheng
type: application
version: 0.1.0
appVersion: "1.0.0"
