{{ if .Values.argocd.create }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.argocd.project.name | default "cluster-manager" }}
  namespace: {{ .Values.argocd.namespace | default "cluster-manager" }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: {{ .Values.argocd.project.description | default "cluster manager Project" }}
  {{- if .Values.argocd.project.sourceRepos }}
  sourceRepos:
    {{- toYaml .Values.argocd.project.sourceRepos | nindent 4 }}
  {{- else }}
  sourceRepos:
    - "*"
  {{- end }}
  {{- if .Values.argocd.project.destinations }}
  destinations:
    {{- toYaml .Values.argocd.project.destinations | nindent 4 }}
  {{- else }}
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  {{- end }}
  {{- if .Values.argocd.project.clusterResourceWhitelist }}
  clusterResourceWhitelist:
    {{- toYaml .Values.argocd.project.clusterResourceWhitelist | nindent 4 }}
  {{- else }}
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  {{- end }}
  {{- if .Values.argocd.project.namespaceResourceWhitelist }}
  namespaceResourceWhitelist:
    {{- toYaml .Values.argocd.project.namespaceResourceWhitelist | nindent 4 }}
  {{- else }}
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  {{- end }}
  {{- if .Values.argocd.project.roles }}
    {{- toYaml .Values.argocd.project.roles | nindent 4 }}
  {{- else }}
  roles:
    - name: gitsop-ci-role
      description: "gitops git role and policy"
      policies:
        - "p, proj:{{ .Values.argocd.project.name | default "cluster-manager" }}:{{ .Values.argocd.project.name | default "cluster-manager" }}, applications, get, {{ .Values.argocd.project.name | default "cluster-manager" }}/*, allow"
        - "p, proj:{{ .Values.argocd.project.name | default "cluster-manager" }}:{{ .Values.argocd.project.name | default "cluster-manager" }}, applications, override, {{ .Values.argocd.project.name | default "cluster-manager" }}/*, allow"
        - "p, proj:{{ .Values.argocd.project.name | default "cluster-manager" }}:{{ .Values.argocd.project.name | default "cluster-manager" }}, applications, sync, {{ .Values.argocd.project.name | default "cluster-manager" }}/*, allow"
        - "p, proj:{{ .Values.argocd.project.name | default "cluster-manager" }}:{{ .Values.argocd.project.name | default "cluster-manager" }}, exec, * , {{ .Values.argocd.project.name | default "cluster-manager" }}/*, allow"
  {{- end}}
{{- end }}